### ISSUE TITLE
Outbound calls by updater

### ISSUE THREAD

**Issue by SlimeDog** [ZombieStriker/WorldChangeScreenRemover#4]
Spigot 1.12.2
WCSR 1.0.3

My network tracker shows multiple calls to api.github.com and 192.30.253.116 by _me.zombie_striker.wcsr.GithubUpdater.autoUpdate_, even though
```
# Updater by ArsenArsen 
# Global config
# Sets should updates be downloaded globally
update: false
```

My servers are now blocking them, but I thought you would like to know.

**Comment by ZombieStriker** [comment]
I swapped over to a new updater (for github instead of the ArsenArsen's Bukkitdev one). That explains the API.github site. I'm not sure about the other IP, as there is nothing in the code that references that IP.

In the new update, I've added a new check to disable the autoupdating in the config.yml.

Sorry for any inconveniences swapping the updater may have caused.
